cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'caskroom/fonts'

brew 'ack'
brew 'ag'
brew 'coreutils'
brew 'fd'
brew 'fpp'
brew 'git'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libgit2'
brew 'openssl'
brew 'readline'
brew 'puma/puma/puma-dev'
brew 'reattach-to-user-namespace'
brew 'roundup'
brew 's-search'
brew 'spaceman-diff'
brew 'spark'
brew 'tig'
brew 'tree'
brew 'unrar'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh'


cask 'font-fira-code'
cask 'font-fira-mono'
cask 'font-fira-mono-for-powerline'
cask 'font-fira-sans'

cask 'firefox'
cask 'google-chrome'
cask 'kap'
cask '1password'
cask 'iterm2'
cask 'ngrok'
cask 'spotify'
cask 'slack'
cask 'teamviewer'
cask 'tunnelbear'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
