tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/versions'
cask 'java'
cask 'anybar'
brew 'chruby'
brew 'cmake'
brew 'openssl'
brew 'erlang'
brew 'elixir'
brew 'exercism'
brew 'git'
brew 'fzf'
brew 'imagemagick'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'go'
brew 'heroku'
brew 'lua'
brew 'htop'
brew 'memcached', restart_service: true
brew 'node'
brew 'postgresql', restart_service: true
brew 'redis', restart_service: true
brew 'ruby-install'
brew 'ruby'
brew 'rsync'
brew 'the_silver_searcher'
brew 'tree'
brew 'vim'
brew 'wrk'
brew 'zsh'
