tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/versions'
cask 'anybar'
cask 'java'
cask 'font-dosis'
cask 'font-lato'
cask 'font-yanone-kaffeesatz'
cask 'font-quicksand'
cask 'font-source-sans-pro'
cask 'font-source-code-pro'
cask 'font-sniglet'
cask 'font-roboto'
cask 'font-roboto-condensed'
brew 'cmake'
brew 'chromedriver', restart_service: false
brew 'graphviz'                                  # To build ERD diagrams
brew 'openssl'
brew 'erlang'
brew 'elixir'
brew 'exercism'
brew 'git'
brew 'fzf'
brew 'ffmpeg'
brew 'thefuck'
brew 'highlight'                                 # Syntax highlight code snippets
brew 'hivemind'                                  # Process manager (Procfile based)
brew 'imagemagick'
brew 'readline'
brew 'sqlite'
brew 'shellcheck'                                # Linter for shell scripts
brew 'python'
brew 'go'
brew 'heroku'
brew 'lua'
brew 'htop'
brew 'memcached', restart_service: true
brew 'node'
brew 'postgresql', restart_service: true
brew 'redis', restart_service: true
brew 'ruby-build'
brew 'ruby'
brew 'rbenv'
brew 'rsync'
brew 'the_silver_searcher'
brew 'tree'
brew 'vim'
brew 'wrk'                                       # Simple web app benchmarking
brew 'yarn'
brew 'zsh'
