let g:ruby_path = system('echo $HOME/.rbenv/shims') " speed up vim-ruby (rbenv)
set rtp+=/usr/local/opt/fzf

" Plugins (require vim-plug)
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'mileszs/ack.vim'
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'lifepillar/vim-solarized8'
Plug 'tpope/vim-commentary'                " serious commenting in/out
Plug 'tpope/vim-eunuch'                    " unix file manipulations

" languages
Plug 'elixir-lang/vim-elixir'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'slim-template/vim-slim'
Plug 'fatih/vim-go'
call plug#end()

" Plugin specific settings
let NERDTreeShowHidden=1
let g:vim_markdown_folding_disabled = 1    " disable auto-folding
let g:vim_markdown_new_list_item_indent=2  " indent lists by 2 spaces in .md files
set laststatus=2
let g:lightline = {'colorscheme': 'solarized'}
let g:closetag_filenames = "*.html.*"
let g:go_highlight_functions = 1           " syntax highlighting for all the go stuff
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

" General
set nocompatible                           " vim not vi mode
set mouse=a                                " allow mouse in all modes
set autoread                               " automatically reload buffers
set autowrite                              " automatically save files
set nobackup                               " disable backups
set nowritebackup                          " write file in place
set noswapfile                             " no .swap files
set backspace=indent,eol,start             " make backspace behave normal
set visualbell                             " don't beep
set noerrorbells                           " don't beep
set novb                                   " no flashing of screen

" Search
set incsearch                              " incremental search
set ignorecase                             " seach case insensitive...
set smartcase                              " ... unless it contains capital letter
set wildignore+=*/tmp/*,*.so,*.swp,*.zip   " ignore tmp directories
let g:ackprg = 'ag --nogroup --nocolor --column'

" Navigation
nnoremap <C-J> <C-W><C-J>        " faster split navigation
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set scrolloff=2                  " start scrolling 3 lines off the border
map <C-n> :NERDTreeToggle<CR>    " toggle NERDTree with ctrl n
nnoremap <Tab> :bnext<CR>        " cylce through buffers
nnoremap <c-p> :FZF<cr>          " use fzf like ctrl p

" Editing
set expandtab                              " use softtabs
set tabstop=2
set shiftwidth=2
set shiftround
filetype plugin indent on                  " filetype matching indention
syntax on                                  " syntax highlighting
set wrap linebreak nolist                  " line wrapping
set breakindent                            " indent wrapped lines

" Spelling
autocmd FileType gitcommit setlocal spell        " spell check for git commit messages
autocmd BufRead,BufNewFile *.md setlocal spell   " spell check for markdown files
set complete+=kspell                             " autocomplete words

" Appearance
set ruler                                  " display cursor position
set colorcolumn=80                         " highlight 80 char column
set number                                 " show line numbers
set termguicolors
colorscheme solarized8_dark
set background=dark
set noshowmode                             " hide default status line

" Functions
fun! StripTrailingWhiteSpace()             " Strip trailing whitespaces (where needed)
  if &ft =~ 'markdown'
    return
  endif
  %s/\s\+$//e
endfun
autocmd bufwritepre * :call StripTrailingWhiteSpace()
