# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="pure"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=7

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/dotfiles/zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker docker-compose zsh-syntax-highlighting git-open)

source $ZSH/oh-my-zsh.sh

# Load Calculator
autoload -Uz zcalc

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="/usr/local/sbin:$PATH" # Expand path for homebrew sbin
export PATH="$PATH:/usr/local/bin/elixir" # Add Elixir for development
export PATH="$PATH:/$ZSH_CUSTOM/plugins/git-open" # Add git-open
export PATH="/usr/local/opt/mysql@5.6/bin:$PATH" # Add legacy mysql to path
export PATH="/usr/local/opt/openssl/bin:$PATH" # Add openssl
export GOPATH=$HOME/code/go # Add Go Path
export JRUBY_OPTS="--dev -J-Xmx2G"
export DOTS=$HOME/dotfiles

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Supress beep for autocompletion
setopt nolistbeep

# Supress duplicates in CTR-R
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# rbenv
eval "$(rbenv init -)"

# fzf fuzzy search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# solarized colors for fzf
export FZF_DEFAULT_OPTS='
  --color=bg+:#073642,spinner:#719e07,hl:#586e75
  --color=fg:#839496,header:#586e75,info:#cb4b16,pointer:#719e07
  --color=marker:#719e07,fg+:#839496,prompt:#719e07,hl+:#719e07
'

# fbr - checkout git branch (including remote branches)
br() {
  local branches branch
  branches=$(git branch --all | grep -v HEAD) &&
  branch=$(echo "$branches" |
           fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

# gifify - convert a video into a gif
# example: gifify movie.mov
gifify() {
  local video=$1
  local name=${video:r}
  local gif=${name}.gif
  ffmpeg -ss 00:00:00.000 -i $video -r 10 -s 1280x960 -t 00:00:10.000 $gif
}

# alias for thefuck (correct previous commands)
eval $(thefuck --alias)

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Aliases
alias at="atom ./"
alias backup="bash ~/dotfiles/scripts/backup.sh"
alias be="bundle exec"
