#!/bin/bash
readonly HOMEBREW_URL="https://raw.githubusercontent.com/Homebrew/install/master/install"
readonly OH_MY_ZSH_URL="https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
readonly MACOS_DEFAULTS="$HOME/dotfiles/scripts/macos.sh"

# exit immediately if a command exits with non-zero
set -e

. "$HOME/dotfiles/scripts/print.sh"

update_shell() {
  local shell_path="/usr/local/bin/zsh"
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    info "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells" 2>&1 \
      | print_info
  fi
  sudo chsh -s "$shell_path" "$USER" 2>&1 \
    | print_info
  success "Using zsh from homebrew"
}

set_defaults() {
  source $MACOS_DEFAULTS 2>&1 | print_info
  success "Set macOS defaults"
}

set_computername() {
  user "How should this computer be called?"
  read -e name
  sudo scutil --set ComputerName "$name"
  sudo scutil --set LocalHostName "$name"
  success "Set computername to $name"
}

install_oh_my_zsh() {
  if [ ! -d "$HOME/.oh-my-zsh" ]; then
    info "Installing OH MY ZSH"
    sh -c "$(curl -fsSL $OH_MY_ZSH_URL)"
  fi
  success "OH MY ZSH installed"
}

. "$HOME/dotfiles/scripts/homebrew.sh"
update_shell
set_defaults
set_computername
. "$HOME/dotfiles/scripts/asdf.sh"
install_oh_my_zsh
. "$HOME/dotfiles/scripts/neovim.sh"
