# frozen_string_literal: true

tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'
tap 'pmeinhardt/tools'

# Required to install `wxmac@3.1.5`. Remove these extra
# formulae as soon `wxmac@3.2` is released.
# http://www.wxwidgets.org/
# https://github.com/Homebrew/homebrew-core/blob/master/Formula/wxmac.rb
tap 'dominicletz/homebrew-extra'

# code apps
cask 'firefox'
cask 'iterm2'
cask 'rectangle'          # window management

# dev apps
cask 'chromedriver'
cask 'docker'
# cask 'google-chrome'
cask 'insomnia'           # postman alternative
cask 'visual-studio-code'

# other apps
# cask '1password'
cask 'imageoptim'         # remove exif-data from images
cask 'keepingyouawake'
# cask 'slack'
cask 'spotify'
cask 'vlc'
cask 'zoom'

# fonts
cask 'font-dosis'
cask 'font-quicksand'

# packages
brew 'autoconf'            # for installing erlang
brew 'coreutils'           # GNU file, shell and text utilities
brew 'gpg'                 # GNU privacy packages
brew 'htop'
brew 'nmap'                # Network Mapper - network discovery and security auditing
brew 'openssl'
brew 'readline'
brew 'rsync'
brew 'tree'
brew 'watch'               # execute command periodically
brew 'wget'
brew 'wxmac@3.1.5'         # for starting erlang observer / debugger (OTP 24)

# dev packages
brew 'ansible'
brew 'fd'                         # faster alternative fo `find`
brew 'fzf'                        # command line fuzzy finder
brew 'git'
brew 'git-quick-stats'            # git repo stats
brew 'hadolint'                   # lint dockerfiles
brew 'highlight'                  # utility for converting code to rtf
brew 'jq'                         # format JSON
brew 'overmind'                   # Process manager (Procfile based)
brew 'ripgrep'                    # search tool
brew 'shellcheck'                 # Linter for shell scripts
brew 'tmux'
brew 'watchman'                   # for filewatchers
brew 'yarn'                       # run with --ignore-engines if incompatible with node version
brew 'zsh'

# postgis packages
brew 'geos'
brew 'json-c'
brew 'proj'

# work related packages
brew 'pmeinhardt/tools/hmm'

# services
brew 'redis', restart_service: true
