#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# To debug, uncomment:
# set -o xtrace

SCRIPT_DIR=$(dirname "$0")
# shellcheck source=./lib/utils.sh
source "$SCRIPT_DIR/lib/utils.sh"

DOTS_DIR="$( cd -- "$(dirname "$(dirname "$0")")" >/dev/null 2>&1 ; pwd -P )"
DIR_PATTERN=(! -name ".git" -and ! -name "homebrew" -and ! -name "script")
TOPICS=$(find "$DOTS_DIR" -maxdepth 1 -type d "${DIR_PATTERN[@]}")
readonly DOTS_DIR
readonly DIR_PATTERN
readonly TOPICS

function install_topic() {
  local topic=$1
  cd "$topic"
  find . -maxdepth 1 -name install.sh \
    | while read -r installer; do $installer; done
  find . -maxdepth 1 -name symlink.sh \
    | while read -r symlink; do $symlink; done
}

info "INSTALL TOPICS…"

# TODO: refactor these out
export local OVERWRITE_SYMLINKS=false
export local BACKUP_SYMLINKS=false
export local SKIP_SYMLINKS=false

install_topic "$DOTS_DIR/homebrew"

for topic in ${TOPICS[*]}; do
  install_topic "$topic"
done
