#!/usr/bin/env bash

# Install topics
# Usage: script/install [topic]

set -o errexit
set -o nounset
set -o pipefail

# To debug, uncomment:
# set -o xtrace

SCRIPT_DIR=$(dirname "$0")
# shellcheck source=./lib/utils.sh
source "$SCRIPT_DIR/lib/utils.sh"

DOTS_DIR="$( cd -- "$(dirname "$(dirname "$0")")" >/dev/null 2>&1 ; pwd -P )"
DIR_PATTERN=(! -name ".git" -and ! -name "homebrew" -and ! -name "script")
TOPICS=$(find "$DOTS_DIR" -maxdepth 1 -type d "${DIR_PATTERN[@]}")
readonly DOTS_DIR
readonly DIR_PATTERN
readonly TOPICS

function install_topic() {
  local topic=$1
  cd "$topic"
  find . -maxdepth 1 -name install.sh \
    | while read -r installer; do $installer; done
  find . -maxdepth 1 -name symlink.sh \
    | while read -r symlink; do $symlink; done
  find . -maxdepth 1 -name finalize.sh \
    | while read -r finalize; do $finalize; done
}

if [ $# -eq 0 ]; then
  info "INSTALL ALL TOPICS…"

  # Evaluate the Brewfile first
  install_topic "$DOTS_DIR/homebrew"

  # then, install the other topics.
  for topic in ${TOPICS[*]}; do
    install_topic "$topic"
  done
else
  info "INSTALL $1…"
  install_topic "$DOTS_DIR/$1"
fi
