#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR=$(dirname "$0")

# shellcheck source=./lib/utils.sh
source "$SCRIPT_DIR/lib/utils.sh"

COMPUTER_NAME=$(scutil --get ComputerName)

ask "HOW SHOULD THIS COMPUTER BE CALLED? (currently: $COMPUTER_NAME)"
read -r name

info "SETTING COMPUTER NAME to '$name'…"
sudo scutil --set ComputerName "$name"
sudo scutil --set LocalHostName "$name"

"$SCRIPT_DIR/install"
