#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR=$(dirname "$0")

# shellcheck source=./lib/utils.sh
source "$SCRIPT_DIR/lib/utils.sh"

cd "$(dirname "$0")/.."
info "UPDATE GIT SUBMODULES…"
git submodule update --remote
